# Κάνοντας compile το <foo>_test.c με μια υλοποίηση <foo>.c του
# συγκεκριμένου τύπου, παράγουμε ένα tets για την υλοποίηση αυτή.

# Υλοποιήσεις μέσω HashTable: ADTMap
#
UsingHashTable_ADTMap_test_OBJS		= ADTMap_test.o $(MODULES)/UsingHashTable/ADTMap.o


# Ο βασικός κορμός του Makefile
include ../common.mk