name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: make UsingHashTable_ADTMap_test
        run: cd tests && make UsingHashTable_ADTMap_test
        continue-on-error: true

      - name: Run UsingHashTable_ADTMap_test
        run: (cd tests && ./UsingHashTable_ADTMap_test) || true
