name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: make

      - name: Run UsingHashWithSet_ADTMap_test
        run: (cd tests && ./UsingHashWithSet_ADTMap_test) || true

      - name: Run UsingCuckooHash_ADTMap_test
        run: (cd tests && ./UsingCuckooHash_ADTMap_test) || true
